package models

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/ibrahimijai/go-http-server/db"
)

// Postgres satisfies URLStore backed by a pgx connection pool. SQL lives in
// db/query.sql and is generated by sqlc (run `make sqlc`); this file owns the
// pool lifecycle and translates DB errors into our sentinels.
type Postgres struct {
	pool *pgxpool.Pool
	q    *db.Queries
}

var _ URLStore = (*Postgres)(nil)

// NewPostgres connects and pings, failing fast at startup on a bad DSN.
func NewPostgres(ctx context.Context, dsn string) (*Postgres, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("creating pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("pinging database: %w", err)
	}
	return &Postgres{pool: pool, q: db.New(pool)}, nil
}

func (p *Postgres) Close() { p.pool.Close() }

func (p *Postgres) Save(ctx context.Context, code, target string) error {
	err := p.q.SaveURL(ctx, db.SaveURLParams{Code: code, Target: target})
	if err != nil {
		// Translate Postgres' unique-violation (SQLSTATE 23505) into ErrConflict.
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return ErrConflict
		}
		return fmt.Errorf("inserting url: %w", err)
	}
	return nil
}

func (p *Postgres) GetByCode(ctx context.Context, code string) (string, error) {
	target, err := p.q.GetTargetByCode(ctx, code)
	switch {
	case errors.Is(err, pgx.ErrNoRows):
		return "", ErrNotFound
	case err != nil:
		return "", fmt.Errorf("querying url: %w", err)
	}
	return target, nil
}
