// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        int64
	Code      string
	Target    string
	CreatedAt pgtype.Timestamptz
}
