// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetTargetByCode(ctx context.Context, code string) (string, error)
	SaveURL(ctx context.Context, arg SaveURLParams) error
}

var _ Querier = (*Queries)(nil)
