// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const getTargetByCode = `-- name: GetTargetByCode :one
SELECT target FROM urls WHERE code = $1
`

func (q *Queries) GetTargetByCode(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, getTargetByCode, code)
	var target string
	err := row.Scan(&target)
	return target, err
}

const saveURL = `-- name: SaveURL :exec
INSERT INTO urls (code, target) VALUES ($1, $2)
`

type SaveURLParams struct {
	Code   string
	Target string
}

func (q *Queries) SaveURL(ctx context.Context, arg SaveURLParams) error {
	_, err := q.db.Exec(ctx, saveURL, arg.Code, arg.Target)
	return err
}
