// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countByEmailOrPhone = `-- name: CountByEmailOrPhone :one
SELECT count(*) FROM users
WHERE email = $1 OR phone = $2
`

type CountByEmailOrPhoneParams struct {
	Email string `json:"email"`
	Phone string `json:"phone"`
}

func (q *Queries) CountByEmailOrPhone(ctx context.Context, arg CountByEmailOrPhoneParams) (int64, error) {
	row := q.db.QueryRow(ctx, countByEmailOrPhone, arg.Email, arg.Phone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id, first_name, last_name, password, email, phone, role, token, refresh_token
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING user_id, first_name, last_name, password, email, phone, role, token, refresh_token, created_at, updated_at
`

type CreateUserParams struct {
	UserID       uuid.UUID `json:"user_id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Password     string    `json:"password"`
	Email        string    `json:"email"`
	Phone        string    `json:"phone"`
	Role         string    `json:"role"`
	Token        *string   `json:"token"`
	RefreshToken *string   `json:"refresh_token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Password,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.Token,
		arg.RefreshToken,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, first_name, last_name, password, email, phone, role, token, refresh_token, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, first_name, last_name, password, email, phone, role, token, refresh_token, created_at, updated_at FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Token,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, first_name, last_name, password, email, phone, role, token, refresh_token, created_at, updated_at FROM users
ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Password,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Token,
			&i.RefreshToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokens = `-- name: UpdateTokens :exec
UPDATE users
SET token = $2, refresh_token = $3, updated_at = now()
WHERE user_id = $1
`

type UpdateTokensParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Token        *string   `json:"token"`
	RefreshToken *string   `json:"refresh_token"`
}

func (q *Queries) UpdateTokens(ctx context.Context, arg UpdateTokensParams) error {
	_, err := q.db.Exec(ctx, updateTokens, arg.UserID, arg.Token, arg.RefreshToken)
	return err
}
